### ISSUE TITLE
Add a permission for muting users "forever"

### ISSUE THREAD

**Issue by laCour** [shdwp/MuteMan#2]
While being able to mute users both by time as well as indefinitely is great, it would be awesome to have a separate permission that allows players to mute another player forever.

This allows groups to only mute users by time, and not forever. This would also allow for groups to mute both with time and forever.

**Comment by shdwp** [comment]
I made this in MuteMan v1.1. Currently this version is needs for approval. 
Wait a sec, and you can download it from http://dev.bukkit.org/server-mods/muteman/
Thanks
